### ISSUE TITLE
create the alien cache directory for ref.mugqic

### ISSUE THREAD

**Issue by poquirion** [c3g/puppet-magic_castle#3]
The directory need to be here `/scratch/cvmfs_alien_cache/ref.mugqic` it can be created on the management node.

It also needs to be owned by cvmfs:cvmfs-reserved with `uid:gid` `uid=13000004(cvmfs) gid=8000131(cvmfs-reserved)`

The cvmfs user needs to be created before the installation of the cvmfs repo by yum. 

The user needs to exist on the login node and compute node so it could be added in the `/etc/passwd` file of these nodes but it could also be done with freeipa, but then we will have to make sure that the freeipa is running with the cvmfs uset register before we install the cvmfs package. If we go with the `/etc/passwd` it might be easier to add the user in the main magic-castle repo...

On the management node we need to have these command ran:

```
mkdir -p /scratch/cvmfs_alien_cache/ref.mugqic
chown 13000004:8000131 /scratch/cvmfs_alien_cache/ref.mugqic
```

**Comment by rptaylor** [comment]
https://wiki.computecanada.ca/staff/CVMFS_client_setup#Service_account_synchronization
